### ISSUE TITLE
1.7 support

### ISSUE THREAD

**Issue by ericchiang** [ericchiang/k8s#52]
Known issues:

* Custom resource definitions are in a different repo.
* Was ObjectMeta removed from v1?

**Comment by JorritSalverda** [comment]
Any update on this? I use version `v0.2.0` and have trouble watching/listing secrets, services and ingress objects. They all fail with an error similar to

```
decode error status: payload is not a kubernetes protobuf object 
panic: runtime error: invalid memory address or nil pointer dereference 
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x990804]
```

**Comment by ericchiang** [comment]
@JorritSalverda this https://github.com/ericchiang/k8s/issues/46?

**Comment by JorritSalverda** [comment]
@ericchiang indeed with legacy authorization enabled it works fine. I'll try and fix my **rbac** roles so i can disable **abac**. Thanks for pointing that out.

**Comment by justinliew** [comment]
I'm getting the same `decode error status: payload is not a kubernetes protobuf object` error when trying to create pods in AWS. 
If I'm using RBAC, how do I specify the service account when calling `kubeClient.CoreV1().CreatePod()`?

Thanks!

**Comment by etiennetremel** [comment]
@justinliew I would suggest you to read this section about RBAC:
https://kubernetes.io/docs/admin/authorization/rbac/#service-account-permissions

Something similar to this should be enough depending on your requirements: 
```
# define role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: my-cluster-role
rules:
- apiGroups: [""] 
  resources:
  - pods
  verbs:
  - create
---
# apply role to service account
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: my-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-cluster-role
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: my-namespace
```

Hope that help.
