### ISSUE TITLE
context doesn't have a user

### ISSUE THREAD

**Issue by InTheCloudDan** [ericchiang/k8s#59]
I'm trying to connect externally to a minikube cluster using

```
func loadClient(kubeconfigPath string) (*k8s.Client, error) {
	data, err := ioutil.ReadFile(kubeconfigPath)
	if err != nil {
		return nil, fmt.Errorf("read kubeconfig: %v", err)
	}

	// Unmarshal YAML into a Kubernetes config object.
	var config k8s.Config
	if err := yaml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("unmarshal kubeconfig: %v", err)
	}
	return k8s.NewClient(&config)
}
```

I'm getting an error: `2017/10/14 19:21:17 context doesn't have a user`

Output shows I do have a user configured though:
```
kubectl config get-contexts
CURRENT   NAME       CLUSTER    AUTHINFO   NAMESPACE
*         minikube   minikube   minikube

kubectl config current-context
minikube
```
Seems like I shouldn't be getting this error with that info, unless there's some part I'm missing.

**Comment by ericchiang** [comment]
Can you share your raw kubeconfig (without sensitive fields)? Hard to debug without that :)

**Comment by InTheCloudDan** [comment]
Sure, sorry about that!

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/dan/.minikube/ca.crt
    server: https://192.168.99.101:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/dan/.minikube/client.crt
    client-key: /Users/dan/.minikube/client.key
```
