### ISSUE TITLE
Parsing kubeconfig's certificate-authority-data fails

### ISSUE THREAD

**Issue by bechtoldt** [ericchiang/k8s#81]
certificate-authority-data (k8s. Cluster.CertificateAuthorityData) normally is a base64 string, but the current code somehow tries to translate it into ``[]uint8``:

```
yaml: unmarshal errors:
  line 6: cannot unmarshal !!str `LS0tLS1...` into []uint8
```

**Comment by ericchiang** [comment]
What yaml library are you using? Can you share a reproducible test case?

**Comment by bechtoldt** [comment]
see
* https://github.com/inovex/trovilo/blob/master/client/client.go#L7
* https://github.com/inovex/trovilo/blob/master/client/client.go#L22

I will provide an example config later this weekend.

**Comment by Ulexus** [comment]
I am using [go-yaml/yaml](https://github.com/go-yaml/yaml), and I have the same issue.  (yaml)String -> (go)[]uint8 apparently doesn't work with its `Unmarshal()`.

An example YAML file which fails (though it really only matters that `certificate-authority-data` is defined):

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: Qk9HVVMgQ2VydCBBdXRob3JpdHkgRGF0YQ==
    server: https://192.168.101.101
  name: gke_PROJECTID
contexts:
- context:
    cluster: gke_PROJECTID
    user: gke_PROJECTID
  name: gke_PROJECTID
current-context: gke_PROJECTID
kind: Config
preferences: {}
users:
- name: gke_PROJECTID
  user:
    auth-provider:
      config:
        access-token: ya29.REMOVED
        cmd-args: config config-helper --format=json
        cmd-path: /home/MY-USER/google-cloud-sdk/bin/gcloud
        expiry: 2017-07-23T17:07:48Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
